spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sekohan
    password: sekohan
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: oracle
  servlet:
    multipart:
      enabled: true
      location: src/main/upload
      max-request-size: 30MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: dim95985@gmail.com
    password: kghc vluw ouie gvjo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 7070

com:
  sekohan:
    upload:
      userProfilePath: src/main/upload/user
      bannerPath: src/main/upload/banner
      prodecutPath : src/main/upload/product

application:
  security:
    jwt:
      secretKey: 25432A462D4A614E645267556A586E3272357538782F413F4428472B4B625065
      expiration: 900000 #15분
      refreshExpiration: 86400000 #24시간