
server:
  port: 7070

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: BOOTUSER
    password: BOOTUSER
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: oracle
  servlet:
    multipart:
      enabled: true
      location: src/main/upload/
      max-request-size: 30MB
      max-file-size: 10MB

com:
  sekohan:
    upload:
      path: src/main/upload/